name: StackExchange-Notifier workflow file

# on:
#   schedule:
#     # Runs at 12am IST
#     - cron: '10 15 * * *'
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Notify-me:
    name: Send mail to me
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        # env:
        #   TO_MAIL: ${{ vars.TO_MAIL }}
        #   APP_PASSWORD: ${{ vars.APP_PASSWORD }}
        #   FROM_MAIL: ${{ vars.FROM_MAIL }}
      - name: Install Dependencies
        run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      # - name: Run the code
        # run: python ${{ github.workspace }}/main.py
      - name: print vars
        run: echo "${{vars.VAR_1}}"
