name: StackExchange-Notifier

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  StackExchange-Notifier:
    name: StackExchange-Notifier
    runs-on: ubuntu-latest
    steps:
      - uses: yasirfaizahmed/StackExchange-Notifier@master    # This repo is good :)
        with:
          TO_MAIL: ${{ secrets.TO_MAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          FROM_MAIL: ${{ secrets.FROM_MAIL }}
