name: StackExchange-Notifier workflow file

# on:
#   schedule:
#     # Runs at 12am IST
#     - cron: '10 15 * * *'
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Notify-me:
    name: Send mail to me
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    env:
          TO_MAIL: ${{ vars.TO_MAIL_v }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD_v }}
          FROM_MAIL: ${{ vars.FROM_MAIL_v }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: python -m pip install -r ${{ github.workspace }}/requirements.txt
      - name: Run the code
        run: python ${{ github.workspace }}/main.py
      # - name: print vars
      #   run: echo "${{env.TO_MAIL}}"
      # - name: print sec
      #   run: echo "${{env.APP_PASSWORD}}"
